export const kunTableRowProps = {
  item: Object,
  index: Number,
  headers: Array,
  showExpand: Boolean,
  showSelect: Boolean,
  isExpanded: Boolean,
  isSelected: Boolean,
  rowClass: String,
  trClass: String,
  tdClass: String,
  selectedClass: String,
  stripedClass: String,
  hasActions: Boolean,
  actionsAlign: String,
  loading: { type: [Boolean, Object], default: false },
  rowClassCondition: [String, Function],
  customSlots: Object,
}
