export const kunFileInputProps = {
  modelValue: [File, Array],
  multiple: Boolean,
  clearable: Boolean,
  chips: Boolean,
  showSize: [Boolean, Number],
  label: String,
  dirty: {
    type: Boolean,
    default: true,
  },
  disabled: Boolean,
  error: Boolean,
  errorMessages: [String, Array],
  hint: String,
  persistentHint: Boolean,
  counter: Boolean,
  counterString: String,
  counterSizeString: String,
  prependIcon: [String, Object, Function, Array],
  appendIcon: [String, Object, Function, Array],
  prependInnerIcon: [String, Object, Function, Array],
  appendInnerIcon: [String, Object, Function, Array],
  prependInnerClass: String,
  appendInnerClass: String,
  clearIcon: [String, Object, Function, Array],
  iconSize: {
    type: String,
    default: 'text-base',
  },
  variant: {
    type: String,
    default: 'filled',
  },
  rules: {
    type: Array,
    default: () => [],
  },
}
