export const kunDatePickerProps = {
  modelValue: { type: [Date, Array, String], default: null },
  range: { type: Boolean, default: false },
  label: { type: String, default: '' },
  placeholder: { type: String, default: '' },
  disabled: { type: Boolean, default: false },
  errorMessage: { type: String, default: '' },
  autoApply: { type: Boolean, default: true },
  mode: { type: String, default: 'date' },
  enableTime: { type: Boolean, default: false },
  enableSeconds: { type: Boolean, default: false },
  startDate: { type: [Date, String], default: null },
  startTime: { type: [String, Object], default: null },
  minDate: { type: Date, default: null },
  maxDate: { type: Date, default: null },
  locale: { type: String, default: 'es-ES' },
  valueFormat: { type: String, default: null },
  format: { type: String, default: null },
  displayFormat: { type: String, default: null },
  formats: { type: Object, default: () => null },
  width: { type: [String, Number], default: null },
  calendarWidth: { type: [String, Number], default: 320 },
  fullWidth: { type: Boolean, default: false },
  align: { type: String, default: 'left' },
  daySize: { type: String, default: '2rem' },
  fontSize: { type: String, default: '0.875rem' },
  maxHeight: { type: String, default: '400px' },
  inputClass: { default: '' },
  dialogClass: { default: '' },
}
