export const kunTooltipProps = {
  class: [String, Array, Object],
  text: String,
  location: { type: String, default: 'top' },
  openOn: { type: String, default: 'hover' },
  transition: { type: String, default: 'fade' },
  disabled: Boolean,
  delay: { type: [Number, String], default: 0 },
  closeDelay: { type: [Number, String], default: 100 },
  textColor: { type: String, default: 'text-ui' },
  bgColor: { type: String, default: 'bg-surface-dark' },
  rounded: { type: String, default: 'rounded' },
  textSize: { type: String, default: 'text-sm' },
  dist: { type: [Number, Object], default: () => ({ x: 0, y: 8 }) },
  flip: { type: Boolean, default: true },
}
