/**
 * Genera el barrel de componentes y la augmentación GlobalComponents.
 *
 * - Descubre componentes con la misma regla que el ex plugin virtual
 *   (`<dir>/src/components/<dir>.vue` existe).
 * - Escribe `src/components/index.ts` con re-exports explícitos.
 * - Reescribe en `src/index.ts`:
 *   - `export * from 'virtual:kun-ui/auto-exports'` →
 *     `export * from './components/index.js'` (type + runtime reales).
 *   - Bloque `declare module 'vue' { interface GlobalComponents ... }`
 *     para autocompletado de tags con `app.use(KunUI)`.
 *
 * Todo lo generado es type-only o re-exports estáticos ya presentes en el
 * bundle: no cambia el JS emitido ni el tamaño del bundle.
 *
 * Uso: `pnpm run generate:barrel` (o `node scripts/generate-barrel.ts`).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const componentsDir = path.join(rootDir, 'src', 'components');
const indexTsPath = path.join(rootDir, 'src', 'index.ts');
const barrelPath = path.join(componentsDir, 'index.ts');

const START_MARK = '// === AUTO-GENERATED:GLOBAL-COMPONENTS:START ===';
const END_MARK = '// === AUTO-GENERATED:GLOBAL-COMPONENTS:END ===';

function discoverComponents(): string[] {
  return fs
    .readdirSync(componentsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((dir) =>
      fs.existsSync(path.join(componentsDir, dir, 'src', 'components', `${dir}.vue`)),
    )
    .sort((a, b) => a.localeCompare(b));
}

function buildBarrel(names: string[]): string {
  const lines = [
    '// AUTO-GENERATED by scripts/generate-barrel.ts — do not edit by hand.',
    "// Re-exports explícitos (runtime + tipos). Equivale al ex módulo virtual",
    "// 'virtual:kun-ui/auto-exports' pero resoluble por consumidores.",
    '',
  ];
  for (const name of names) {
    lines.push(`export { default as ${name} } from './${name}/src/components/${name}.vue';`);
  }
  lines.push(
    '',
    '// Tipos públicos de props (uniones literales, interfaces). Type-only: no',
    '// afecta el bundle. Permite `import type { KunBtnVariant } from ...`.',
  );
  for (const name of names) {
    for (const f of propsFilesFor(name)) {
      const base = f.replace(/\.ts$/, '');
      lines.push(`export type * from './${name}/src/composables/${base}.js';`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

/** Archivos *Props.ts del componente (misma regla que generate-docs.ts). */
function propsFilesFor(dir: string): string[] {
  const compDir = path.join(componentsDir, dir, 'src', 'composables');
  if (!fs.existsSync(compDir)) return [];
  return fs
    .readdirSync(compDir)
    .filter((f) => f.endsWith('Props.ts'))
    .sort((a, b) => a.localeCompare(b));
}

function buildGlobalComponentsBlock(names: string[]): string {
  const lines = [
    START_MARK,
    '// AUTO-GENERATED by scripts/generate-barrel.ts — do not edit by hand.',
    '// Permite autocompletado de tags (<KunBtn ...>) y props con app.use(KunUI).',
    "declare module 'vue' {",
    '  interface GlobalComponents {',
  ];
  for (const name of names) {
    lines.push(
      `    ${name}: typeof import('./components/${name}/src/components/${name}.vue')['default'];`,
    );
  }
  lines.push('  }', '}', END_MARK, '');
  return lines.join('\n');
}

function main(): void {
  const names = discoverComponents();
  if (!names.length) {
    throw new Error('No se encontraron componentes en src/components');
  }

  fs.writeFileSync(barrelPath, buildBarrel(names), 'utf-8');
  console.log(`✓ src/components/index.ts (${names.length} componentes)`);

  let indexTs = fs.readFileSync(indexTsPath, 'utf-8');

  const virtualLine = "export * from 'virtual:kun-ui/auto-exports';";
  if (indexTs.includes(virtualLine)) {
    indexTs = indexTs.replace(virtualLine, "export * from './components/index.js';");
  } else if (!indexTs.includes("export * from './components/index.js';")) {
    throw new Error('src/index.ts no contiene ni el export virtual ni el barrel; revisión manual requerida');
  }

  const block = buildGlobalComponentsBlock(names);
  const startIdx = indexTs.indexOf(START_MARK);
  const endIdx = indexTs.indexOf(END_MARK);
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = indexTs.slice(0, startIdx);
    const after = indexTs.slice(endIdx + END_MARK.length);
    indexTs = `${before}${block}${after}`;
  } else {
    if (!indexTs.endsWith('\n')) indexTs += '\n';
    indexTs = `${indexTs}\n${block}`;
  }

  fs.writeFileSync(indexTsPath, indexTs, 'utf-8');
  console.log(`✓ src/index.ts (barrel + GlobalComponents ×${names.length})`);
}

main();
