/**
 * KunUI - Vue.js 3 Component Library with Tailwind CSS
 *
 * @package adverich-kun-ui
 * @documentation For AI agents documentation, see: AGENTS.md
 *
 * @example
 * // Installation
 * npm install adverich-kun-ui
 *
 * @example
 * // Global registration
 * import { createApp } from 'vue'
 * import KunUI from 'adverich-kun-ui'
 * import 'adverich-kun-ui/dist/adverich-kun-ui.css'
 *
 * const app = createApp(App)
 * app.use(KunUI)
 *
 * @example
 * // Individual component import
 * import { KunBtn, KunTextField, KunDialog } from 'adverich-kun-ui'
 */

import { defineAsyncComponent, type App, type AsyncComponentLoader, type Component } from 'vue'
import './styles/style.css'
import './utils/utils.js'

// Config global
import { kunConfig, KUN_CONFIG_KEY, type KunConfigOptions } from './config/kunConfig.js'

// Asíncrono para uso manual
const asyncModules = import.meta.glob('./components/**/src/components/*.vue');

function extractComponentName(path: string): string {
  return (path.split('/').at(-1) as string).replace('.vue', '');
}

// 1. Carga asincrónica para registro bajo demanda
export const components = Object.fromEntries(
  Object.entries(asyncModules).map(([path, comp]) => {
    const name = extractComponentName(path);
    return [name, defineAsyncComponent(comp as AsyncComponentLoader)];
  })
);

export interface KunUIInstallOptions {
    skipIfRegistered?: boolean;
    config?: KunConfigOptions;
}

// Registro global
export function install(app: App, options: KunUIInstallOptions = {}): void {
  const { skipIfRegistered = true, config = {} } = options;

  // Aplicar configuración global si se proporciona
  if (Object.keys(config).length > 0) {
    kunConfig.configure(config);
  }

  // Proveer config a toda la app para injection
  app.provide(KUN_CONFIG_KEY, kunConfig.current);

  const allComponents = import.meta.glob('./components/**/src/components/*.vue', { eager: true });

  Object.entries(allComponents).forEach(([path, component]) => {
    const name = extractComponentName(path);
    if (!skipIfRegistered || !app._context.components[name]) {
      app.component(name, (component as { default: Component }).default);
    }
  });
}

export * from './components/index.js';

// Exportar config para uso externo
export { kunConfig, useKunConfig, resolveConfigValue } from './config/kunConfig.js';
export { kunDocumentConfig } from './config/kunDocumentConfig.js';

// Composables headless
export {
  useKunDragAndDrop,
  resolveItemKey,
} from './components/KunDragAndDrop/src/composables/useKunDragAndDrop.js';
export {
  useKunCarousel,
  KUN_CAROUSEL_KEY,
} from './components/KunCarousel/src/composables/kunCarouselContext.js';
export {
  createKunToast,
  provideKunToast,
  useToast,
} from './components/KunToast/src/composables/useToast.js';
export type {
  ToastAction,
  ToastConfig,
  ToastItem,
  KunToastSystem,
} from './components/KunToast/src/composables/useToast.js';

// 4. Exportación por defecto
export default {
  install,
  ...components
};

// === AUTO-GENERATED:GLOBAL-COMPONENTS:START ===
// AUTO-GENERATED by scripts/generate-barrel.ts — do not edit by hand.
// Permite autocompletado de tags (<KunBtn ...>) y props con app.use(KunUI).
declare module 'vue' {
  interface GlobalComponents {
    KunAlert: typeof import('./components/KunAlert/src/components/KunAlert.vue')['default'];
    KunAppbar: typeof import('./components/KunAppbar/src/components/KunAppbar.vue')['default'];
    KunAppbarTitle: typeof import('./components/KunAppbarTitle/src/components/KunAppbarTitle.vue')['default'];
    KunAutocomplete: typeof import('./components/KunAutocomplete/src/components/KunAutocomplete.vue')['default'];
    KunAvatar: typeof import('./components/KunAvatar/src/components/KunAvatar.vue')['default'];
    KunBadge: typeof import('./components/KunBadge/src/components/KunBadge.vue')['default'];
    KunBtn: typeof import('./components/KunBtn/src/components/KunBtn.vue')['default'];
    KunCard: typeof import('./components/KunCard/src/components/KunCard.vue')['default'];
    KunCardActions: typeof import('./components/KunCardActions/src/components/KunCardActions.vue')['default'];
    KunCardItem: typeof import('./components/KunCardItem/src/components/KunCardItem.vue')['default'];
    KunCardSubtitle: typeof import('./components/KunCardSubtitle/src/components/KunCardSubtitle.vue')['default'];
    KunCardText: typeof import('./components/KunCardText/src/components/KunCardText.vue')['default'];
    KunCardTitle: typeof import('./components/KunCardTitle/src/components/KunCardTitle.vue')['default'];
    KunCarousel: typeof import('./components/KunCarousel/src/components/KunCarousel.vue')['default'];
    KunCarouselSlide: typeof import('./components/KunCarouselSlide/src/components/KunCarouselSlide.vue')['default'];
    KunCheckbox: typeof import('./components/KunCheckbox/src/components/KunCheckbox.vue')['default'];
    KunChip: typeof import('./components/KunChip/src/components/KunChip.vue')['default'];
    KunClock: typeof import('./components/KunClock/src/components/KunClock.vue')['default'];
    KunCol: typeof import('./components/KunCol/src/components/KunCol.vue')['default'];
    KunColorPicker: typeof import('./components/KunColorPicker/src/components/KunColorPicker.vue')['default'];
    KunContainer: typeof import('./components/KunContainer/src/components/KunContainer.vue')['default'];
    KunCurrency: typeof import('./components/KunCurrency/src/components/KunCurrency.vue')['default'];
    KunDatePicker: typeof import('./components/KunDatePicker/src/components/KunDatePicker.vue')['default'];
    KunDialog: typeof import('./components/KunDialog/src/components/KunDialog.vue')['default'];
    KunDivider: typeof import('./components/KunDivider/src/components/KunDivider.vue')['default'];
    KunDragAndDrop: typeof import('./components/KunDragAndDrop/src/components/KunDragAndDrop.vue')['default'];
    KunDragAndDropHandle: typeof import('./components/KunDragAndDropHandle/src/components/KunDragAndDropHandle.vue')['default'];
    KunDragAndDropItem: typeof import('./components/KunDragAndDropItem/src/components/KunDragAndDropItem.vue')['default'];
    KunDrawer: typeof import('./components/KunDrawer/src/components/KunDrawer.vue')['default'];
    KunFileInput: typeof import('./components/KunFileInput/src/components/KunFileInput.vue')['default'];
    KunForm: typeof import('./components/KunForm/src/components/KunForm.vue')['default'];
    KunIcon: typeof import('./components/KunIcon/src/components/KunIcon.vue')['default'];
    KunInfiniteScroll: typeof import('./components/KunInfiniteScroll/src/components/KunInfiniteScroll.vue')['default'];
    KunList: typeof import('./components/KunList/src/components/KunList.vue')['default'];
    KunListGroup: typeof import('./components/KunListGroup/src/components/KunListGroup.vue')['default'];
    KunListImg: typeof import('./components/KunListImg/src/components/KunListImg.vue')['default'];
    KunListItem: typeof import('./components/KunListItem/src/components/KunListItem.vue')['default'];
    KunListItemAction: typeof import('./components/KunListItemAction/src/components/KunListItemAction.vue')['default'];
    KunListItemAvatar: typeof import('./components/KunListItemAvatar/src/components/KunListItemAvatar.vue')['default'];
    KunListItemSubtitle: typeof import('./components/KunListItemSubtitle/src/components/KunListItemSubtitle.vue')['default'];
    KunListItemText: typeof import('./components/KunListItemText/src/components/KunListItemText.vue')['default'];
    KunListItemTitle: typeof import('./components/KunListItemTitle/src/components/KunListItemTitle.vue')['default'];
    KunListSubheader: typeof import('./components/KunListSubheader/src/components/KunListSubheader.vue')['default'];
    KunLoaderCircular: typeof import('./components/KunLoaderCircular/src/components/KunLoaderCircular.vue')['default'];
    KunMenu: typeof import('./components/KunMenu/src/components/KunMenu.vue')['default'];
    KunModalFooter: typeof import('./components/KunModalFooter/src/components/KunModalFooter.vue')['default'];
    KunNumberField: typeof import('./components/KunNumberField/src/components/KunNumberField.vue')['default'];
    KunRadio: typeof import('./components/KunRadio/src/components/KunRadio.vue')['default'];
    KunRadioGroup: typeof import('./components/KunRadioGroup/src/components/KunRadioGroup.vue')['default'];
    KunRelationMatrix: typeof import('./components/KunRelationMatrix/src/components/KunRelationMatrix.vue')['default'];
    KunRow: typeof import('./components/KunRow/src/components/KunRow.vue')['default'];
    KunSelect: typeof import('./components/KunSelect/src/components/KunSelect.vue')['default'];
    KunSkeleton: typeof import('./components/KunSkeleton/src/components/KunSkeleton.vue')['default'];
    KunSlider: typeof import('./components/KunSlider/src/components/KunSlider.vue')['default'];
    KunSpacer: typeof import('./components/KunSpacer/src/components/KunSpacer.vue')['default'];
    KunSwitch: typeof import('./components/KunSwitch/src/components/KunSwitch.vue')['default'];
    KunTable: typeof import('./components/KunTable/src/components/KunTable.vue')['default'];
    KunTableServerSide: typeof import('./components/KunTableServerSide/src/components/KunTableServerSide.vue')['default'];
    KunTabs: typeof import('./components/KunTabs/src/components/KunTabs.vue')['default'];
    KunTextarea: typeof import('./components/KunTextarea/src/components/KunTextarea.vue')['default'];
    KunTextField: typeof import('./components/KunTextField/src/components/KunTextField.vue')['default'];
    KunToast: typeof import('./components/KunToast/src/components/KunToast.vue')['default'];
    KunToolbar: typeof import('./components/KunToolbar/src/components/KunToolbar.vue')['default'];
    KunTooltip: typeof import('./components/KunTooltip/src/components/KunTooltip.vue')['default'];
    KunVirtualScroller: typeof import('./components/KunVirtualScroller/src/components/KunVirtualScroller.vue')['default'];
  }
}
// === AUTO-GENERATED:GLOBAL-COMPONENTS:END ===


