export default {
  modelValue: { type: [String, Number], default: '' },
  type: { type: String, default: 'text' },
  placeholder: { type: String, default: '' },
  label: { type: String, default: '' },
  dirty: { type: Boolean, default: false },
  prefix: { type: String, default: '' },
  suffix: { type: String, default: '' },
  rounded: { type: String, default: 'rounded' },
  error: { type: Boolean, default: false },
  errorMessage: { type: String, default: '' },
  rules: { type: Array, default: () => [] },
  disabled: { type: Boolean, default: false },
  readonly: { type: Boolean, default: false },
  clearable: { type: Boolean, default: false },
  debounce: { type: Number, default: 300 },
  maxlength: { type: [Number, String], default: null },
  counter: { type: Boolean, default: false },
  hint: { type: String, default: '' },
  persistentHint: { type: Boolean, default: false },
  hideDetails: { type: Boolean, default: false },
  validateOnBlur: { type: Boolean, default: false },
  prependInnerClass: String,
  appendInnerClass: String,
  textColor: { type: String, default: 'text-black dark:text-white' },
  labelColor: { type: String, default: 'text-black/80 dark:text-white/80' },
  placeholderColor: { type: String, default: 'placeholder-black/60 dark:placeholder-white/60' },
  bgInput: { type: String, default: 'bg-slate-200 dark:bg-slate-800' },
}
